// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0X2iAqgksU5RTkmoTtFpg12qA4q1s_nQ',
    appId: '1:425764720471:web:b3f8675d70917bbb64b812',
    messagingSenderId: '425764720471',
    projectId: 'flutter-web-portfolio-website',
    authDomain: 'flutter-web-portfolio-website.firebaseapp.com',
    databaseURL: 'https://flutter-web-portfolio-website.firebaseio.com',
    storageBucket: 'flutter-web-portfolio-website.appspot.com',
    measurementId: 'G-PGXYKE7K7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU6mBog4S4XdFk-6mx_pymhTRKtuN6iY8',
    appId: '1:425764720471:android:da2ba9f0f4b8b33764b812',
    messagingSenderId: '425764720471',
    projectId: 'flutter-web-portfolio-website',
    databaseURL: 'https://flutter-web-portfolio-website.firebaseio.com',
    storageBucket: 'flutter-web-portfolio-website.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC99YvM-v8a3grDCBIEMfjfTK5cFEf0BRw',
    appId: '1:425764720471:ios:c7e0595bc2d2268464b812',
    messagingSenderId: '425764720471',
    projectId: 'flutter-web-portfolio-website',
    databaseURL: 'https://flutter-web-portfolio-website.firebaseio.com',
    storageBucket: 'flutter-web-portfolio-website.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );
}
